name: Update Star Rank

on:
  push:
    branches: [ main, master ]
  schedule:
    # 每2小时运行一次
    - cron: '0 */2 * * *'
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  update-rank:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4
        
    - name: Run ranking script
      run: |
        echo "Current working directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Files in scripts directory:"
        ls -la scripts/
        echo "Checking repos.txt:"
        head -20 repos.txt
        echo "Running ranking script..."
        chmod +x scripts/update_rank.py
        python scripts/update_rank.py
        echo "Ranking script completed successfully"
        
    - name: Check generated files
      run: |
        ls -la
        echo "Checking if index.html was generated:"
        if [ -f "index.html" ]; then
          echo "✅ index.html exists"
          echo "File size: $(wc -c < index.html) bytes"
          echo "First few lines:"
          head -10 index.html
        else
          echo "❌ index.html not found"
          exit 1
        fi
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update star rankings [skip ci]"
          git push
          echo "Changes committed and pushed successfully"
        fi
